name: .NET

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: 'src/StreamStruct/StreamStruct.csproj'
  TEST_PATH: 'src/StreamStruct.Tests/StreamStruct.Tests.csproj'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
      nuget-artifact-name: ${{ steps.upload-nuget.outputs.artifact-name }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ${{ env.TEST_PATH }} --configuration Release --no-build --verbosity normal
    
    - name: Create NuGet packages
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --output ./packages
    
    - name: List package files
      run: ls -la ./packages/
    
    - name: Publish
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish
    
    - name: Upload build artifacts
      id: upload
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
      uses: actions/upload-artifact@v4
      with:
        name: streamstruct-${{ github.sha }}
        path: |
          - ./publish
          - ./packages
    
    - name: Upload NuGet packages
      id: upload-nuget
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages-${{ github.sha }}
        path: ./packages

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-and-test.outputs.artifact-name }}
        path: ./release
    
    - name: Download NuGet packages
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-and-test.outputs.nuget-artifact-name }}
        path: ./packages
    
    - name: List downloaded packages
      run: ls -la ./packages/
    
    - name: Publish to NuGet
      run: |
        dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push ./packages/*.snupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./release/*
          ./packages/*
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false